package com.dawson.aaaccount.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dawson.aaaccount.dao.bean.DBConfig;
import com.dawson.aaaccount.dao.bean.DBDayBook;
import com.dawson.aaaccount.dao.bean.DBFamily;
import com.dawson.aaaccount.dao.bean.DBSystemLog;
import com.dawson.aaaccount.dao.bean.DBUser;
import com.dawson.aaaccount.dao.bean.JoinDayBookToUser;
import com.dawson.aaaccount.dao.bean.JoinUserToFamily;

import com.dawson.aaaccount.dao.DBConfigDao;
import com.dawson.aaaccount.dao.DBDayBookDao;
import com.dawson.aaaccount.dao.DBFamilyDao;
import com.dawson.aaaccount.dao.DBSystemLogDao;
import com.dawson.aaaccount.dao.DBUserDao;
import com.dawson.aaaccount.dao.JoinDayBookToUserDao;
import com.dawson.aaaccount.dao.JoinUserToFamilyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBConfigDaoConfig;
    private final DaoConfig dBDayBookDaoConfig;
    private final DaoConfig dBFamilyDaoConfig;
    private final DaoConfig dBSystemLogDaoConfig;
    private final DaoConfig dBUserDaoConfig;
    private final DaoConfig joinDayBookToUserDaoConfig;
    private final DaoConfig joinUserToFamilyDaoConfig;

    private final DBConfigDao dBConfigDao;
    private final DBDayBookDao dBDayBookDao;
    private final DBFamilyDao dBFamilyDao;
    private final DBSystemLogDao dBSystemLogDao;
    private final DBUserDao dBUserDao;
    private final JoinDayBookToUserDao joinDayBookToUserDao;
    private final JoinUserToFamilyDao joinUserToFamilyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBConfigDaoConfig = daoConfigMap.get(DBConfigDao.class).clone();
        dBConfigDaoConfig.initIdentityScope(type);

        dBDayBookDaoConfig = daoConfigMap.get(DBDayBookDao.class).clone();
        dBDayBookDaoConfig.initIdentityScope(type);

        dBFamilyDaoConfig = daoConfigMap.get(DBFamilyDao.class).clone();
        dBFamilyDaoConfig.initIdentityScope(type);

        dBSystemLogDaoConfig = daoConfigMap.get(DBSystemLogDao.class).clone();
        dBSystemLogDaoConfig.initIdentityScope(type);

        dBUserDaoConfig = daoConfigMap.get(DBUserDao.class).clone();
        dBUserDaoConfig.initIdentityScope(type);

        joinDayBookToUserDaoConfig = daoConfigMap.get(JoinDayBookToUserDao.class).clone();
        joinDayBookToUserDaoConfig.initIdentityScope(type);

        joinUserToFamilyDaoConfig = daoConfigMap.get(JoinUserToFamilyDao.class).clone();
        joinUserToFamilyDaoConfig.initIdentityScope(type);

        dBConfigDao = new DBConfigDao(dBConfigDaoConfig, this);
        dBDayBookDao = new DBDayBookDao(dBDayBookDaoConfig, this);
        dBFamilyDao = new DBFamilyDao(dBFamilyDaoConfig, this);
        dBSystemLogDao = new DBSystemLogDao(dBSystemLogDaoConfig, this);
        dBUserDao = new DBUserDao(dBUserDaoConfig, this);
        joinDayBookToUserDao = new JoinDayBookToUserDao(joinDayBookToUserDaoConfig, this);
        joinUserToFamilyDao = new JoinUserToFamilyDao(joinUserToFamilyDaoConfig, this);

        registerDao(DBConfig.class, dBConfigDao);
        registerDao(DBDayBook.class, dBDayBookDao);
        registerDao(DBFamily.class, dBFamilyDao);
        registerDao(DBSystemLog.class, dBSystemLogDao);
        registerDao(DBUser.class, dBUserDao);
        registerDao(JoinDayBookToUser.class, joinDayBookToUserDao);
        registerDao(JoinUserToFamily.class, joinUserToFamilyDao);
    }
    
    public void clear() {
        dBConfigDaoConfig.clearIdentityScope();
        dBDayBookDaoConfig.clearIdentityScope();
        dBFamilyDaoConfig.clearIdentityScope();
        dBSystemLogDaoConfig.clearIdentityScope();
        dBUserDaoConfig.clearIdentityScope();
        joinDayBookToUserDaoConfig.clearIdentityScope();
        joinUserToFamilyDaoConfig.clearIdentityScope();
    }

    public DBConfigDao getDBConfigDao() {
        return dBConfigDao;
    }

    public DBDayBookDao getDBDayBookDao() {
        return dBDayBookDao;
    }

    public DBFamilyDao getDBFamilyDao() {
        return dBFamilyDao;
    }

    public DBSystemLogDao getDBSystemLogDao() {
        return dBSystemLogDao;
    }

    public DBUserDao getDBUserDao() {
        return dBUserDao;
    }

    public JoinDayBookToUserDao getJoinDayBookToUserDao() {
        return joinDayBookToUserDao;
    }

    public JoinUserToFamilyDao getJoinUserToFamilyDao() {
        return joinUserToFamilyDao;
    }

}
