package com.dawson.aaaccount.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dawson.aaaccount.dao.bean.DBFamily;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBFAMILY".
*/
public class DBFamilyDao extends AbstractDao<DBFamily, String> {

    public static final String TABLENAME = "DBFAMILY";

    /**
     * Properties of entity DBFamily.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property LastModifiedTime = new Property(1, java.util.Date.class, "lastModifiedTime", false, "LAST_MODIFIED_TIME");
        public final static Property Number = new Property(2, int.class, "number", false, "NUMBER");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property IsTemp = new Property(4, boolean.class, "isTemp", false, "IS_TEMP");
    }

    private DaoSession daoSession;


    public DBFamilyDao(DaoConfig config) {
        super(config);
    }
    
    public DBFamilyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBFAMILY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"LAST_MODIFIED_TIME\" INTEGER," + // 1: lastModifiedTime
                "\"NUMBER\" INTEGER NOT NULL ," + // 2: number
                "\"NAME\" TEXT," + // 3: name
                "\"IS_TEMP\" INTEGER NOT NULL );"); // 4: isTemp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBFAMILY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBFamily entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        java.util.Date lastModifiedTime = entity.getLastModifiedTime();
        if (lastModifiedTime != null) {
            stmt.bindLong(2, lastModifiedTime.getTime());
        }
        stmt.bindLong(3, entity.getNumber());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getIsTemp() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBFamily entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        java.util.Date lastModifiedTime = entity.getLastModifiedTime();
        if (lastModifiedTime != null) {
            stmt.bindLong(2, lastModifiedTime.getTime());
        }
        stmt.bindLong(3, entity.getNumber());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getIsTemp() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(DBFamily entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public DBFamily readEntity(Cursor cursor, int offset) {
        DBFamily entity = new DBFamily( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // lastModifiedTime
            cursor.getInt(offset + 2), // number
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getShort(offset + 4) != 0 // isTemp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBFamily entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLastModifiedTime(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setNumber(cursor.getInt(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsTemp(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(DBFamily entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(DBFamily entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBFamily entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
